name: Install Nix packages
inputs:
  shell:
    default: true
  instantiated-expression:
    required: false
runs:
  using: composite
  steps:
    - name: Initialize Action
      shell: bash
      run: |
        case "$SHELL" in
        true|1)
          echo "::set-output name=shell-file::shell.nix"
          ;;
        *)
          echo "::set-output name=shell-file::"
          ;;
        esac
      env:
        SHELL: ${{ inputs.shell }}

    - name: Install Nix shell
      uses: diamondburned/cache-install@3c3ac40a3f928c99efd165b900b265b26da4e175
      with:
        auto-optimise: ${{ inputs.auto-optimise }}
        shell-file: ${{ steps.init.outputs.shell-file }}
        instantiated-expression: ${{ inputs.instantiated-expression }}
