name: Check

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  cache-install: diamondburned/cache-install@3c3ac40a3f928c99efd165b900b265b26da4e175

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        uses: ${{ env.cache-install }}
        with:
          shell-file: shell.nix
          auto-optimise: true

  gomod:
    name: Tidy up Go modules
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        id: nix-install
        uses: ${{ env.cache-install }}
        with:
          shell-file: shell.nix
          auto-optimise: true

      - run: go mod tidy
      - run: git diff --exit-code go.mod go.sum

  format:
    name: Format
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        id: nix-install
        uses: ${{ env.cache-install }}
        with:
          shell-file: shell.nix
          auto-optimise: true

      - run: |
          deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
          [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

  lint:
    name: Lint
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        id: nix-install
        uses: ${{ env.cache-install }}
        with:
          shell-file: shell.nix
          auto-optimise: true

      - run: |
          nix-shell --run '
            go vet ./...
            staticcheck ./...
          '

  test:
    name: Test
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        id: nix-install
        uses: ${{ env.cache-install }}
        with:
          shell-file: shell.nix
          auto-optimise: true

      - run: go test -v ./...
