name: Check

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix packages
        uses: ./.github/actions/init-nix
        with:
          shell-file: shell.nix

      - name: Tidy up Go Modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Format
        run: |
          deps="$(for d in $(go list -f {{.Dir}} ./...); { goimports -l $d; })"
          [[ ! "$deps" ]] || printf "Unformatted files: \n%s\n" "$deps"

      - name: Vet
        run: go vet ./...

      - name: staticcheck
        run: staticcheck ./...

      - name: Test
        run: go test -v ./...

