name: Check

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix shell
        uses: ./.github/actions/init-nix
        with:
          shell-file: shell.nix

      - name: Tidy up Go Modules
        run: |
          go mod tidy

          if ! git diff --exit-code go.mod go.sum; then
            echo "::error::Go modules are not tidied"
            exit 1
          fi

      - name: Format
        run: |
          fail=
          go list -f '{{ .Dir }}' | while read -r d; do
            goimports -l "$d" | while read -r f; do
              fail=1
              printf "::error file=%s::%s\n" "$d/$f" "File is not formatted"
            done
          done
          [[ -z "$fail" ]]

      - name: Vet
        run: go vet ./... |& workflowify -e -t vet

      - name: Staticcheck (warnings)
        run: staticcheck ./... || true |& workflowify -w -t staticcheck

      - name: Test
        run: go test -v ./...

