name: Install Nix packages
inputs:
  shell-file:
    required: false
  instantiated-expression:
    required: false
runs:
  using: composite
  steps:
    - name: Install Nix shell
      uses: diamondburned/cache-install@195d4a266f4f336a747cae8f64f6b14c780fc548
      with:
        auto-optimise: ${{ inputs.auto-optimise }}
        shell-file: ${{ inputs.shell-file }}
        instantiated-expression: ${{ inputs.instantiated-expression }}
