name: Install Nix packages
inputs:
  shell-file:
    required: false
  instantiated-expression:
    required: false
runs:
  using: composite
  steps:
    - name: Install Nix shell
      uses: diamondburned/cache-install@de704a19e9f92e70e99dba497f2eb9a32b57b2b6
      with:
        auto-optimise: ${{ inputs.auto-optimise }}
        shell-file: ${{ inputs.shell-file }}
        instantiated-expression: ${{ inputs.instantiated-expression }}
